added --api_key option for moonraker configs with authorization enabled
Annex-Engineering/klipper_estimator pull request #26
Opened 2022-08-25 11:30 UTC by solidrobo

Added header to HTTP request required for authorization. Extra option ```--api_key``` is used to provide the key.

2022-08-25 12:41 UTC, dalegaard requested changes
Hi @solidrobo 

I was expecting there to be more to implementing this, but with the simple API key option it's not too bad it seems.

I've added a few comments to your code.

Best regards,
Lasse

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +    #[clap(long = "api_key")]
This should be `config_moonraker_api_key`.

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +        //let api_key: String = "ef405007c95749cdb55f5c8940e52118".to_string();
Remove comment

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +    api_key: &str,
Take `Option<&str>`.

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +        .header("X-Api-Key", api_key).send()?
It would be better if this was only set when the key is given. Something like:
```rust
let client = reqwest::blocking::Client::new();
let mut req = client.get(url);
if let Some(api_key) = api_key {
  req = req.header("X-Api-Key", api_key);
}
let cfg = req
  .send()?
  ...
```

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +        let mut api_key = "";
Remove this unwrap.

2022-08-25 12:41 UTC, dalegaard commented on tool/src/main.rs
> +            moonraker_config(url, api_key, &mut limits)?;
Use `self.config_moonraker_api_key.as_deref()` instead of `api_key`

2022-08-25 16:21 UTC, solidrobo commented
I did the changes requested

2022-08-26 07:12 UTC, dalegaard commented
Hi @solidrobo 

I ran `cargo fmt` and removed the comment line about a hack, not really sure what that was about?

I'll merge like this, thanks for the contribution!

Best regards,
Lasse

2022-08-26 07:13 UTC, merged